name: scan with KICS docker-runner

on:
  pull_request:
    branches: [master]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-action@fix/path-to-kics
        with:
          path: 'terraform'
          output_path: results.sarif
          ignore_on_exit: results
          platform_type: terraform
          exclude_queries: 0437633b-daa6-4bbc-8526-c0d2443b946e
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
